# Generated by Django 3.2.2 on 2021-05-13 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sunBotApi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='publish',
            new_name='publishing',
        ),
        migrations.RemoveField(
            model_name='event',
            name='ended',
        ),
    ]
