# Generated by Django 3.2.2 on 2021-05-13 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunBotApi', '0002_auto_20210513_2119'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='name',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='event',
            name='publishing',
            field=models.BooleanField(default=False, verbose_name='Публиковать'),
        ),
    ]
