# Generated by Django 3.2.2 on 2021-05-14 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunBotApi', '0003_auto_20210513_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='note',
            field=models.TextField(blank=True, default='', verbose_name='Для примечаний:'),
        ),
        migrations.AddField(
            model_name='user',
            name='note',
            field=models.TextField(blank=True, default='', verbose_name='Для примечаний:'),
        ),
    ]
