# Generated by Django 3.2.2 on 2021-05-14 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunBotApi', '0004_auto_20210514_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='members',
            field=models.TextField(blank=True, default='', verbose_name='Участники:'),
        ),
        migrations.AddField(
            model_name='user',
            name='events',
            field=models.TextField(blank=True, default='', verbose_name='Мероприятия:'),
        ),
    ]
