# Generated by Django 3.2.2 on 2021-05-17 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunBotApi', '0011_auto_20210517_0429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='patronymic',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='user',
            name='surename',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='user',
            name='ticket_code',
            field=models.CharField(max_length=50, unique=True, verbose_name='Код студенческого билета'),
        ),
    ]
