# Generated by Django 3.2.2 on 2021-05-18 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sunBotApi', '0012_auto_20210517_0608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='patronymic',
        ),
        migrations.RemoveField(
            model_name='user',
            name='surename',
        ),
    ]
