# Generated by Django 3.2.2 on 2021-05-18 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunBotApi', '0013_auto_20210518_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='nco',
            field=models.BooleanField(default=True, verbose_name='Для НСО'),
        ),
    ]
